### ISSUE TITLE
implement `yarn start`

### ISSUE THREAD

**Issue by ruoduan-hub** [reese/gatsby-plugin-stork#11]
after  `brew install stork-search/stork-tap/stork` 👇🏻

![image](https://user-images.githubusercontent.com/42793079/112951703-34036580-916e-11eb-9b97-afa2d594fb77.png)

![image](https://user-images.githubusercontent.com/42793079/112952117-bab84280-916e-11eb-8bfa-c27860315f0d.png)

**Comment by reese** [comment]
Are you using some sort of Gatsby Starter project? Is this using the default configuration or do you have a config object you can share?

**Comment by ruoduan-hub** [comment]
> Are you using some sort of Gatsby Starter project? Is this using the default configuration or do you have a config object you can share?


I used the configuration in your "REAME"

```
module.exports = {
    plugins: [
        "gatsby-plugin-stork",
    ]
}
```

```
import React from 'react';
import { StorkInput } from 'gatsby-plugin-stork';

export const YourSearchComponent = () => {
  return (
    <StorkInput placeholder="🔍" />
  );
}
```

**Comment by reese** [comment]
I put up a patch version for this, so if you bump your plugin version to `0.3.1`, this should be resolved. Let me know if you run into any issues, and thanks for the bug report!

**Comment by ruoduan-hub** [comment]
Thank you very much for the solved problem ！
